version: 2.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:       
      - checkout             
      - setup_remote_docker
      - run: 
          name: building the image 
          command: |
            gcloud auth configure-docker --quiet
            SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            docker build -t asia.gcr.io/${GCLOUD_PROJECT_ID}/frontend:${SHORT_HASH} .
      - run:
          name: authenticate with gcloud and pushing to gcr
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            cat ${HOME}/gcloud-service-key.json
            gcloud auth configure-docker --quiet 
            docker push asia.gcr.io/${GCLOUD_PROJECT_ID}/frontend:${SHORT_HASH}
  deploy:
    docker:
      - image: google/cloud-sdk  
    steps: 
      - run: 
          name: authenticate with gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - checkout             
      - run: 
          name: adding deployenment
          command: |
            SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)  
            sed -i "s/IMAGE_TAG/${SHORT_HASH}/" ${HOME}/manifest/application.yaml
            cat ${HOME}/manifest/application.yaml
  
            
