version: 2.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:       
      - checkout             
      - setup_remote_docker
      - run: 
          name: building the image 
          command: |
            gcloud auth configure-docker --quiet
            SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            docker build -t asia.gcr.io/${GCLOUD_PROJECT_ID}/allimages:${SHORT_HASH} .
      - run:
          name: authenticate with gcloud and pushing to gcr
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            cat ${HOME}/gcloud-service-key.json
            gcloud auth configure-docker --quiet 
            docker push asia.gcr.io/${GCLOUD_PROJECT_ID}/allimages:${SHORT_HASH}
      - run:
          name: Kicking Manifest update Deployment pipeline
          command: |
            printf "Triggering an $PROJECT build on the $CIRCLE_BRANCH branch\n\n"

            BUILD_INFO=$(curl -X POST -H -d \
                "{"name": "vik"}" \
                "https://circleci.com/api/v1/project/vikash32/testmanifestrepo?circle-token=$CIRCLE_CI_TOKEN")

            printf "\n\nBuild triggered\n\n"
            printf "Follow the progress of the build on \nhttps://circleci.com/gh/$ORGANIZATION/$PROJECT/tree/$CIRCLE_BRANCH"
  
            
