version: 2.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:       
      - checkout             
      - setup_remote_docker
      - run: 
          name: building the image 
          command: |
            gcloud auth configure-docker --quiet
            SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            docker build -t asia.gcr.io/${GCLOUD_PROJECT_ID}/allimages:${SHORT_HASH} .
            docker image ls 
      - run:
          name: authenticate with gcloud and pushing to gcr
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            cat ${HOME}/gcloud-service-key.json
            gcloud auth configure-docker --quiet 
            echo ${SHORT_HASH}
            echo ${GCLOUD_PROJECT_ID}
            docker image ls 
            docker push asia.gcr.io/${GCLOUD_PROJECT_ID}/allimages:${SHORT_HASH}
          
            
