version: 2.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:       
      - checkout             
      - setup_remote_docker
      - run: 
          name: building the image 
          command: |
            gcloud auth configure-docker --quiet
            SHORT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)      
            docker build -t asia.gcr.io/learningproj3322/allimages:v1 .
      - run:
          name: authenticate with gcloud and pushing to gcr
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            cat ${HOME}/gcloud-service-key.json
            gcloud auth configure-docker --quiet 
            echo $?
            docker push asia.gcr.io/learningproj3322/allimages:v1
          
            
